version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=8
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      # MERCURE_PUBLISH_URL: ${MERCURE_URL:-http://caddy/.well-known/mercure}
      SYMFONY_VERSION:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: database
    ports:
      - 8080:80

  database:
    image: mysql:8.0
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306

  composer:
    image: composer:latest
    command: install
    volumes:
      - .:/app
  node:
    build: docker/node-alpine
    volumes:
      - .:/app:cached
    working_dir: /app
 
volumes:
  php_socket:
 
